# Set update schedule for GitHub Actions

version: 2
registries:
  github-packages-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NPM_READ_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries:
      - github-packages-npm
    groups:
      fortawesome:
        applies-to: version-updates
        patterns:
          - "@fortawesome/*"
      commitlint:
        applies-to: version-updates
        patterns:
          - "@commitlint/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "@eslint/*"
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"
      tailwindcss:
        applies-to: version-updates
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss"
      vitest:
        applies-to: version-updates
        patterns:
          - "@vitest/*"
          - "vitest"
